# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{postgresql-extensions}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = %q{2010-11-30}
  s.description = %q{A whole bunch of extensions the Rails PostgreSQL adapter.}
  s.email = %q{code@zoocasa.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "lib/postgresql_adapter_extensions.rb",
    "lib/postgresql_constraints.rb",
    "lib/postgresql_functions.rb",
    "lib/postgresql_geometry.rb",
    "lib/postgresql_indexes.rb",
    "lib/postgresql_languages.rb",
    "lib/postgresql_permissions.rb",
    "lib/postgresql_rules.rb",
    "lib/postgresql_schemas.rb",
    "lib/postgresql_sequences.rb",
    "lib/postgresql_tables.rb",
    "lib/postgresql_triggers.rb",
    "lib/postgresql_views.rb"
  ]
  s.homepage = %q{http://github.com/zoocasa/postgresql-extensions}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A whole bunch of extensions the Rails PostgreSQL adapter.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

